### ISSUE TITLE
Support for server side rendering

### ISSUE THREAD

**Issue by leoasis** [byronmwong/react-flexbox-layout#10]
Hi!

In our project we've been using this library and have the requirement for server side rendering. We've been thinking about approaches to not depend on `document` but at the same time make React not bail because of different markup being rendered in the server and in the client.

So with @rafaelchiti we've thought about the strategy to move the vendor differences that may cause different markup to static css classes that handle the vendor differences in the css stylesheet.

What do you think about the approach? Is there any concern you see in advance? Would you be willing to accept a PR with an attempt on that?

**Comment by bywo** [comment]
Hey Leonardo,
That sounds like a good strategy. Will the library be responsible for injecting the CSS itself? Or will the user have to include a stylesheet? The library already injects some CSS for EXPAND_CHILD functionality. 

On Fri, Jan 15, 2016 at 3:32 PM -0800, "Leonardo Garcia Crespo" notifications@github.com wrote:

Hi!

In our project we've been using this library and have the requirement for server side rendering. We've been thinking about approaches to not depend on document but at the same time make React not bail because of different markup being rendered in the server and in the client.

So with @rafaelchiti we've thought about the strategy to move the vendor differences that may cause different markup to static css classes that handle the vendor differences in the css stylesheet.

What do you think about the approach? Is there any concern you see in advance? Would you be willing to accept a PR with an attempt on that?

**Comment by leoasis** [comment]
I think auto injecting as you do now is enough, since on the server side we only want to have consistent markup with what the client will render, and we don't really care about CSS (that's often handled outside React).

**Comment by bywo** [comment]
Okay, that works! One downside with the library injecting CSS is that there
may be a flicker of unstyled content, after the first paint, but before JS
is executed.

**Comment by leoasis** [comment]
Oh you're right, and that's a big concern since that's something that will still happen on production... So then I'm more inclined on providing a css file that needs to be included in the consumer app.

**Comment by bywo** [comment]
Ok sounds good. Let's make sure to bump a minor version afterwards.
